### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by DominicWindisch** [DominicWindisch/photobooth-frontend#3]
- rebase on main
- [x] pr1: add IDs to elements for easier private css
- [x] pr2: translation improvements
  - default language fallback
  - linter rule no missing keys
- [x] pr3: Automatic slideshow (polish before)
- [x] pr4: multiple implementations of same type (collage, anime)
- [ ] pr5: printer layout option + printer image picker

**Comment by DominicWindisch** [comment]
That looks like a hell of a lot of work. Hat's off!

![](https://media2.giphy.com/media/lEVZJzy4w15qE/giphy.gif)

**Comment by DominicWindisch** [comment]
![IMG](https://tenor.com/bfmOG.gif)
